In [ ]:
import cv2

In [36]:

import cv2
from tqdm import tqdm
import  os


In [37]:
# feature recognization


In [38]:
train='F:/ipl/train'
predict='F:/newfolder/test1'

In [39]:
n=['cat.1.jpg','dog.2.jpg','cat.3.jpg','dog.4.jpg']
#n.split('.')[0]

In [40]:
def label_img(img):
    label=img.split('.')
    if label[0]=='cat':
        return 0
    elif label[0]=='dog':
        return 1

In [41]:
for i in n:
    r=label_img(i)
    print(r)

0
1
0
1


In [42]:
from random import shuffle
#label_img(n)
train_data=[]
def feature_data():
    for i in tqdm( os.listdir(train)):
    #print(i)
        label=label_img(i)
        path=os.path.join(train,i)
        feature=cv2.imread(path,0)
        feature=cv2.resize(feature,(50,50))
        train_data.append([feature,label])
    shuffle(train_data)
    return train_data

In [43]:
#for i in n:
    #r=label_img(i)
    #print(r)
    

In [46]:
training=feature_data()

100%|██████████| 11346/11346 [02:11<00:00, 86.36it/s] 


In [3]:
#import numpy as npa
#training[0]
#import numpy as np
#training=np.array(training).reshape(11346,2)
#testing=testing_data()




In [48]:
import cv2
from tqdm import tqdm
import  os
from random import shuffle


In [49]:
#train='C:/Users/User/Desktop/projects files/train'
#predict='C:/Users/User/Desktop/projects files/test1'

In [50]:
#def label_img(img):
   # label=img.split('.')
   # if label[0]=='cat':
    #    return 0
   # elif label[0]=='dog':
     #   return 1

In [51]:
from random import shuffle
#label_img(n)
test_data=[]
def testing_data():
    for i in tqdm( os.listdir(predict)):#runing fo rtotal values
    #print(i)
        #label=label_img(i)
        path=os.path.join(predict,i)
        feature=cv2.imread(path,0)
        feature=cv2.resize(feature,(50,50))
        test_data.append([feature])
    shuffle(test_data)
    return test_data

In [52]:
testing=testing_data()

100%|██████████| 12500/12500 [02:39<00:00, 95.13it/s] 


In [53]:
testing

[[array([[165, 158, 114, ..., 142, 153, 154],
         [172, 170, 129, ..., 144, 143, 134],
         [140, 147, 121, ..., 147, 144, 138],
         ...,
         [117, 116,  99, ..., 146, 108, 118],
         [116, 136, 111, ..., 153, 151, 139],
         [111, 115, 110, ..., 138, 125, 117]], dtype=uint8)],
 [array([[110, 110, 114, ..., 143, 144, 155],
         [111, 110, 115, ..., 150, 145, 150],
         [111, 110, 111, ..., 148, 145, 150],
         ...,
         [136, 135, 144, ...,  80,  86,  83],
         [138, 143, 139, ...,  80,  81,  74],
         [135, 140, 134, ...,  74,  68,  70]], dtype=uint8)],
 [array([[27, 27, 28, ..., 52, 39, 24],
         [31, 30, 29, ..., 56, 44, 22],
         [30, 30, 32, ..., 58, 43, 24],
         ...,
         [34, 35, 34, ..., 67, 67, 52],
         [32, 30, 25, ..., 36, 30, 88],
         [31, 27, 27, ..., 56, 75, 90]], dtype=uint8)],
 [array([[246, 245, 244, ...,  27,  36,  36],
         [245, 244, 243, ...,  38,  29,  24],
         [130, 136, 127, .

In [4]:
#training=training.reshape
#

In [54]:
z=np.array([[[2,3,4,5],[1]],[[3,6,2,5],[0]],[[3,6,2,5],[0]]])
z

array([[list([2, 3, 4, 5]), list([1])],
       [list([3, 6, 2, 5]), list([0])],
       [list([3, 6, 2, 5]), list([0])]], dtype=object)

In [55]:
z.shape


(3, 2)

In [56]:
import numpy as np
n=np.zeros([3,5])
n


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
n[0]=1
n

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
z[0][0]

[2, 3, 4, 5]

In [59]:
np.hstack((z[0][0],z[0][1]))

array([2, 3, 4, 5, 1])

In [60]:
for i in range(3):
    n[i]=np.hstack((z[0][0],z[i][1]))
    n

In [78]:
n.shape

(3, 5)

In [61]:
x=n[:,:4]
y=n[:,4:]
y

array([[1.],
       [0.],
       [0.]])

In [62]:
x

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [63]:
#from sklearn.model_selection import train_test_split
#from sklearn.metrics import mean_squared_error,r2_score
#from sklearn.linear_model import LogisticRegression
#xtrain,xtest,ytrain,ytest=train_test_split(X,Y)


In [65]:
z=np.zeros([11346,2501])
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [67]:
for i in range(11346):
    z[i]=np.hstack((training[i][0].ravel(),training[i][1]))
    
    
z    
X=z[:,:-1]
Y=z[:,-1:]

In [70]:
X

array([[134., 131., 132., ...,  94.,  87.,  68.],
       [252., 253., 249., ..., 177., 176., 185.],
       [ 36.,  35.,  36., ..., 247., 248., 249.],
       ...,
       [168., 167., 167., ..., 149., 151., 151.],
       [ 41.,  30.,  29., ...,  22.,  40.,  49.],
       [111., 113., 103., ..., 172., 167., 164.]])

In [71]:
Y

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])